In [1]:
import pandas as pd

In [2]:
vhr_datasets= pd.read_csv("../data/vhr_datasets.csv")

In [3]:
vhr_datasets

,Dataset,Task,Domain,Modalities,GSD (m),N_Samples,Classes,License,In_GEO_Bench_2,In_Pangaea,Link_Reference
0,TreeSatAI,Classification,Tree Species,S2 TS,10,28000,13,CC-BY-4.0,Yes,No,https://essd.copernicus.org/articles/15/681/2023/
1,Dynamic EarthNet,Semantic Segmentation,LULC (temporal),Planet RGB+NIR,3,1000,7,CC-BY-4.0,Yes,Yes,https://earthnets.github.io/
2,FLAIR 2,Semantic Segmentation,LULC,Aerial RGBN+DEM,0.2,8093,13,Open License 2.0,Yes,No,https://ignf.github.io/FLAIR/
3,SpaceNet 2,Semantic Segmentation,Building,Worldview,0.3,9608,2,CC-BY-SA-4.0,Yes,No,https://spacenet.ai/spacenet-buildings-dataset...
4,SpaceNet 7,Semantic Segmentation,Building,Planet Only RGB,3,5692,2,CC-BY-SA-4.0,Yes,Yes,https://spacenet.ai/sn7-challenge/
5,EverWatch,Object Detection,Bird species,Aerial RGB,0.1,5125,9,CC0,Yes,No,https://zenodo.org/records/10811969
6,m-nzcattle,Object Detection,Cattle,Aerial RGB,0.1,655,2,CC-BY-4.0,Yes,No,https://github.com/diababuaiadah/Cattle-Detection
7,Potsdam,Semantic Segmentation,Urban,"Aerial (IR, R, G, DSM)",0.05,38,6,ISPRS Research,No,No,https://www.isprs.org/education/benchmarks/Urb...
8,Vaihingen,Semantic Segmentation,Urban,"Aerial (IR, R, G, DSM)",0.09,33,6,ISPRS Research,No,No,https://www.isprs.org/education/benchmarks/Urb...
9,DOTA V1.0,Object Detection,Aerial Objects,"Google Earth, GF-2, JL-1",0.1 - 4.5,2806,15,Non-commercial,No,No,https://captain-whu.github.io/DOTA/
10,xView2,Change Detection,Disaster / HADR,Maxar (WV-3),0.3,20569,2,xView2 License,No,Yes,https://xview2.org/
11,LEVIR-CD,Change Detection,Building,Google Earth,0.5,637,2,CC-BY-NC-SA 4.0,No,No,https://justcheneng.github.io/LEVIR/
12,UCMerced,Classification,Land Use,Aerial RGB,0.3,2100,21,Public Domain,No,No,http://vision.ucmerced.edu/datasets/landuse.html
13,NWPU-RESISC45,Classification,Scene,Google Earth,0.2 - 30,31500,45,Non-commercial,No,No,https://arxiv.org/abs/1703.00121
14,fMoW,Classification,Land Use (Temporal),"QuickBird, GeoEye, WV",0.5,523846,63,Custom Public,No,No,https://github.com/fMoW/dataset

In [29]:
# git clone https://github.com/The-AI-Alliance/GEO-Bench-2-Leaderboard.git

In [6]:
from pandas.core.frame import DataFrame
vhr_base: DataFrame = pd.read_csv("../data/geo-bench2-results-vhr-base.csv")
vhr_extra: DataFrame = pd.read_csv("../data/geo-bench2-results-vhr-extra.csv")

In [9]:
vhr_extra

,Rank,Model,Category,# Params,Submission,Under 10M Resolution,Spacenet2,Treesatai,Flair2,Dynamic_Earthnet,Spacenet7,Everwatch,Nzcattle
0,1,ConvNext-XLarge-ImageNet,CV-General-FM,390M,114be1f0,86.9 ± 0.1,85.8 ± 0.8,84.2 ± 2.1,65.7 ± 1.8,73.4 ± 1.8,91.5 ± 1.7,96.6 ± 1.3,96.5 ± 1.6
1,2,DinoV3-ConvNext-Large-WEB,CV-General-FM,230M,114be1f0,80.1 ± 0.1,95.3 ± 1.1,92.5 ± 2.5,80.6 ± 2.1,28.3 ± 0.5,92.5 ± 0.3,52.4 ± 1.3,75.0 ± 1.0
2,3,DinoV3-ViT-L-SAT,Native-VHR-GeoFM,300M,114be1f0,77.8 ± 0.2,73.4 ± 0.7,93.7 ± 2.5,98.5 ± 0.3,74.5 ± 9.6,89.2 ± 0.6,36.1 ± 0.9,57.3 ± 0.5
3,4,ConvNext-Large-ImageNet,CV-General-FM,230M,114be1f0,77.0 ± 0.1,81.1 ± 0.6,86.0 ± 2.1,71.7 ± 1.0,44.2 ± 10.5,87.1 ± 1.2,59.7 ± 1.8,82.0 ± 1.0
4,5,DOFA-ViT 300M,Native-VHR-GeoFM,300M,114be1f0,62.7 ± 0.2,64.6 ± 1.3,78.4 ± 0.2,83.2 ± 0.7,40.1 ± 5.2,76.0 ± 1.0,20.0 ± 2.9,44.0 ± 1.2
5,6,DOFA-ViT 300M,Native-VHR-GeoFM,300M,2ce4a907,62.7 ± 0.2,64.6 ± 1.3,78.4 ± 0.2,83.2 ± 0.7,40.1 ± 5.2,76.0 ± 1.0,20.0 ± 2.9,44.0 ± 1.2
6,7,Clay-V1 ViT-B,Native-VHR-GeoFM,100M,114be1f0,60.7 ± 0.2,65.8 ± 1.3,69.4 ± 0.8,65.6 ± 0.3,49.8 ± 4.5,96.9 ± 1.0,43.5 ± 1.6,49.5 ± 1.0
7,8,Clay-V1 ViT-B,Native-VHR-GeoFM,100M,2ce4a907,60.7 ± 0.2,65.8 ± 1.3,69.4 ± 0.8,65.6 ± 0.3,49.8 ± 4.5,96.9 ± 1.0,43.5 ± 1.6,49.5 ± 1.0
8,9,TerraMind-V1-Large,GeoFM-LowRes,300M,114be1f0,55.7 ± 0.1,64.3 ± 1.6,50.6 ± 1.0,42.6 ± 2.7,96.2 ± 1.6,76.9 ± 1.1,30.7 ± 2.6,48.9 ± 0.6
9,10,TerraMind-V1-Large,GeoFM-LowRes,300M,2ce4a907,55.7 ± 0.1,64.3 ± 1.6,50.6 ± 1.0,42.6 ± 2.7,96.2 ± 1.6,76.9 ± 1.1,30.7 ± 2.6,48.9 ± 0.6
10,11,Satlas-SwinB-Naip,Native-VHR-GeoFM,100M,114be1f0,53.4 ± 0.1,49.2 ± 2.5,42.4 ± 1.2,59.0 ± 1.2,5.6 ± 3.6,84.6 ± 0.4,51.0 ± 1.0,69.3 ± 1.3
11,12,Satlas-Swin 100M,GeoFM-LowRes,100M,114be1f0,50.8 ± 0.2,41.5 ± 0.6,47.8 ± 1.3,40.7 ± 0.9,50.8 ± 2.8,84.8 ± 0.4,43.1 ± 4.0,66.9 ± 0.6
12,13,Prithvi-EO-V2 600M TL,GeoFM-LowRes,600M,114be1f0,47.8 ± 0.1,76.3 ± 0.5,52.3 ± 1.3,40.7 ± 1.0,30.8 ± 2.3,90.4 ± 0.9,44.1 ± 0.8,4.6 ± 1.7
13,14,Prithvi-EO-V2 300M TL,GeoFM-LowRes,300M,114be1f0,43.8 ± 0.2,61.8 ± 0.3,35.0 ± 1.9,32.9 ± 3.0,41.7 ± 3.1,81.4 ± 0.1,29.5 ± 1.1,52.6 ± 2.4
14,15,TerraMind-V1-Base,GeoFM-LowRes,100M,114be1f0,42.1 ± 0.1,41.0 ± 1.8,39.8 ± 0.9,40.5 ± 0.2,34.1 ± 11.8,75.4 ± 0.7,28.2 ± 2.1,45.7 ± 1.3
15,16,Resnet50-ImageNet,CV-General-FM,25M,114be1f0,36.1 ± 0.1,52.8 ± 1.4,28.7 ± 3.4,42.6 ± 2.3,23.2 ± 1.9,81.5 ± 0.3,21.6 ± 1.1,28.9 ± 1.3
16,17,Resnet50-DeCUR,GeoFM-LowRes,25M,114be1f0,24.3 ± 0.1,3.3 ± 1.6,20.8 ± 4.9,18.7 ± 0.6,54.7 ± 0.9,72.8 ± 1.0,3.9 ± 2.3,30.7 ± 0.9