In [13]:
import pandas as pd

In [14]:
vhr_datasets= pd.read_csv("../data/vhr_datasets.csv")

In [15]:
vhr_datasets

,Dataset,Task,Domain,Modalities,GSD (m),N_Samples,Classes,License,In_GEO_Bench_2,In_Pangaea,Link_Reference
0,TreeSatAI,Classification,Tree Species,S2 TS,10,28000,13,CC-BY-4.0,Yes,No,https://essd.copernicus.org/articles/15/681/2023/
1,Dynamic EarthNet,Semantic Segmentation,LULC (temporal),Planet RGB+NIR,3,1000,7,CC-BY-4.0,Yes,Yes,https://earthnets.github.io/
2,FLAIR 2,Semantic Segmentation,LULC,Aerial RGBN+DEM,0.2,8093,13,Open License 2.0,Yes,No,https://ignf.github.io/FLAIR/
3,SpaceNet 2,Semantic Segmentation,Building,Worldview,0.3,9608,2,CC-BY-SA-4.0,Yes,No,https://spacenet.ai/spacenet-buildings-dataset...
4,SpaceNet 7,Semantic Segmentation,Building,Planet Only RGB,3,5692,2,CC-BY-SA-4.0,Yes,Yes,https://spacenet.ai/sn7-challenge/
5,EverWatch,Object Detection,Bird species,Aerial RGB,0.1,5125,9,CC0,Yes,No,https://zenodo.org/records/10811969
6,m-nzcattle,Object Detection,Cattle,Aerial RGB,0.1,655,2,CC-BY-4.0,Yes,No,https://github.com/diababuaiadah/Cattle-Detection
7,Potsdam,Semantic Segmentation,Urban,"Aerial (IR, R, G, DSM)",0.05,38,6,ISPRS Research,No,No,https://www.isprs.org/education/benchmarks/Urb...
8,Vaihingen,Semantic Segmentation,Urban,"Aerial (IR, R, G, DSM)",0.09,33,6,ISPRS Research,No,No,https://www.isprs.org/education/benchmarks/Urb...
9,DOTA V1.0,Object Detection,Aerial Objects,"Google Earth, GF-2, JL-1",0.1 - 4.5,2806,15,Non-commercial,No,No,https://captain-whu.github.io/DOTA/
10,xView2,Change Detection,Disaster / HADR,Maxar (WV-3),0.3,20569,2,xView2 License,No,Yes,https://xview2.org/
11,LEVIR-CD,Change Detection,Building,Google Earth,0.5,637,2,CC-BY-NC-SA 4.0,No,No,https://justcheneng.github.io/LEVIR/
12,UCMerced,Classification,Land Use,Aerial RGB,0.3,2100,21,Public Domain,No,No,http://vision.ucmerced.edu/datasets/landuse.html
13,NWPU-RESISC45,Classification,Scene,Google Earth,0.2 - 30,31500,45,Non-commercial,No,No,https://arxiv.org/abs/1703.00121
14,fMoW,Classification,Land Use (Temporal),"QuickBird, GeoEye, WV",0.5,523846,63,Custom Public,No,No,https://github.com/fMoW/dataset

In [28]:
# vhr_datasets = ['spacenet2', 'treesatai', 'flair2', 'dynamic_earthnet', 'spacenet7', 'everwatch', 'nzcattle']
vhr_datasets = ['spacenet2', 'treesatai', 'flair2', 'dynamic_earthnet', 'spacenet7']

In [29]:
# git clone https://github.com/The-AI-Alliance/GEO-Bench-2-Leaderboard.git

In [30]:
import glob
import os 
repo_path = "/Users/krschap/code/personal/GEO-Bench-2-Leaderboard/results/*/results_and_parameters.csv"
files = glob.glob(repo_path)

df_list = []
for f in files:
    df = pd.read_csv(f)
    df['submission'] = os.path.basename(os.path.dirname(f)) # hash
    df_list.append(df)

df_all = pd.concat(df_list, ignore_index=True)

In [31]:
df_all

,dataset,Metric,test metric,mlflow_run_name,mlflow_run_id,mlflow_run_status,Seed,experiment_id,experiment_name,index,...,backbone,early_stop_patience,n_trials,partition_name,data_percentages,batch_size_selection,weight_decay,partition name,frozen_or_full_ft,submission
0,treesatai,Multilabel_F1_Score,0.566198,treesatai_205,514579a0cb4547bfba8e12a862141747,FINISHED,205,775284793786667309,final_main_satlas_resnet50_sentinel2_si_ms_satlas,0,...,satlas_resnet50_sentinel2_si_ms_satlas,10.0,16,default,100,HPO,0.01,100%,full_ft,114be1f0-5a41-43a5-b4e6-7fb683bc01ec
1,treesatai,Multilabel_F1_Score,0.569279,treesatai_2007,8fd6e4a16794471f9ef0969e5fa534ef,FINISHED,2007,775284793786667309,final_main_satlas_resnet50_sentinel2_si_ms_satlas,0,...,satlas_resnet50_sentinel2_si_ms_satlas,10.0,16,default,100,HPO,0.01,100%,full_ft,114be1f0-5a41-43a5-b4e6-7fb683bc01ec
2,treesatai,Multilabel_F1_Score,0.582307,treesatai_1829,97191ec68050405cafc05a4e6f9a0541,FINISHED,1829,775284793786667309,final_main_satlas_resnet50_sentinel2_si_ms_satlas,0,...,satlas_resnet50_sentinel2_si_ms_satlas,10.0,16,default,100,HPO,0.01,100%,full_ft,114be1f0-5a41-43a5-b4e6-7fb683bc01ec
3,treesatai,Multilabel_F1_Score,0.574095,treesatai_913,dcf1d5274f0e473e85f2462716db9862,FINISHED,913,775284793786667309,final_main_satlas_resnet50_sentinel2_si_ms_satlas,0,...,satlas_resnet50_sentinel2_si_ms_satlas,10.0,16,default,100,HPO,0.01,100%,full_ft,114be1f0-5a41-43a5-b4e6-7fb683bc01ec
4,treesatai,Multilabel_F1_Score,0.588385,treesatai_2254,fda6f39f3e404c61a2c109d07739d428,FINISHED,2254,775284793786667309,final_main_satlas_resnet50_sentinel2_si_ms_satlas,0,...,satlas_resnet50_sentinel2_si_ms_satlas,10.0,16,default,100,HPO,0.01,100%,full_ft,114be1f0-5a41-43a5-b4e6-7fb683bc01ec
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2660,so2sat,Overall_Accuracy,0.565923,so2sat_2254,5cf8d611c8e343acb0eb2c3ee77527c6,FINISHED,2254,772544555532204168,final_ablation_frozen_terramind_v1_large,0,...,terramind_v1_large,10.0,16,default,100,HPO,0.01,100%,frozen,80100fc6-dc1a-4514-b946-341157eaf816
2661,so2sat,Overall_Accuracy,0.572008,so2sat_205,68a30d291d8a4b88b3e703580ca49c51,FINISHED,205,772544555532204168,final_ablation_frozen_terramind_v1_large,0,...,terramind_v1_large,10.0,16,default,100,HPO,0.01,100%,frozen,80100fc6-dc1a-4514-b946-341157eaf816
2662,so2sat,Overall_Accuracy,0.578093,so2sat_2007,85cbaec573ae4e7fb5d0924985af943e,FINISHED,2007,772544555532204168,final_ablation_frozen_terramind_v1_large,0,...,terramind_v1_large,10.0,16,default,100,HPO,0.01,100%,frozen,80100fc6-dc1a-4514-b946-341157eaf816
2663,so2sat,Overall_Accuracy,0.583164,so2sat_1829,9fb75a3f2eda4bbcb89f85c868b04b81,FINISHED,1829,772544555532204168,final_ablation_frozen_terramind_v1_large,0,...,terramind_v1_large,10.0,16,default,100,HPO,0.01,100%,frozen,80100fc6-dc1a-4514-b946-341157eaf816
2664,so2sat,Overall_Accuracy,0.566937,so2sat_913,f6338289e0dd4503bbbeadf561f62d74,FINISHED,913,772544555532204168,final_ablation_frozen_terramind_v1_large,0,...,terramind_v1_large,10.0,16,default,100,HPO,0.01,100%,frozen,80100fc6-dc1a-4514-b946-341157eaf816

In [32]:
df_vhr = df_all[df_all['dataset'].isin(vhr_datasets)]
df_mean = df_vhr.groupby(['backbone', 'submission', 'dataset'])['test metric'].mean().unstack().reset_index()

df_mean['mean_score'] = df_mean[vhr_datasets].mean(axis=1) * 100 
for col in vhr_datasets:
    if col in df_mean:
        df_mean[col] = df_mean[col] * 100


df_final = df_mean.sort_values(by='mean_score', ascending=False).reset_index(drop=True)
df_final.insert(0, 'Rank', df_final.index + 1)

cols = ['Rank', 'backbone', 'submission', 'mean_score'] + [d for d in vhr_datasets if d in df_final.columns]
df_final = df_final[cols]

In [33]:
df_final

dataset,Rank,backbone,submission,mean_score,spacenet2,treesatai,flair2,dynamic_earthnet,spacenet7
0,1,dinov3_vitl16,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,60.129299,87.354866,66.381547,54.734964,30.873911,61.301205
1,2,convnext_xlarge_fb_in22k,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,58.874877,87.848221,65.091771,50.031909,29.527643,61.874843
2,3,dinov3_convnext_large,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,58.196389,88.268851,66.051079,52.275095,22.223591,62.163332
3,4,clay_v1_base,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,58.005124,87.037758,62.845060,50.160167,26.735407,63.247230
4,5,clay_v1_base,2ce4a907-7ae3-45d3-a07a-558f8d0d758b,58.005124,87.037758,62.845060,50.160167,26.735407,63.247230
5,6,convnext_large_fb_in22k,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,57.839705,87.705082,65.036383,50.943720,24.763739,60.749600
6,7,terramind_v1_large,2ce4a907-7ae3-45d3-a07a-558f8d0d758b,57.420302,86.857867,60.691178,46.779042,34.511208,58.262216
7,8,terramind_v1_large,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,57.420302,86.857867,60.691178,46.779042,34.511208,58.262216
8,9,dofa_large_patch16_224,2ce4a907-7ae3-45d3-a07a-558f8d0d758b,57.300489,86.969211,64.092865,52.667296,24.817884,57.955189
9,10,dofa_large_patch16_224,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,57.300489,86.969211,64.092865,52.667296,24.817884,57.955189
10,11,dofa_base_patch16_224,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,56.938493,86.321046,64.068927,49.898880,26.202240,58.201371
11,12,satlas_swin_b_sentinel2_si_ms,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,55.955350,86.026306,60.242350,46.809101,26.549942,60.149050
12,13,prithvi_eo_v2_600_tl,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,55.653173,87.451705,60.863388,46.182790,22.119544,61.648438
13,14,dinov3_vitl16,80100fc6-dc1a-4514-b946-341157eaf816,55.610873,86.180357,54.108535,49.004094,29.540854,59.220525
14,15,satlas_resnet50_sentinel2_si_ms_satlas,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,55.474958,85.917609,57.605295,45.387639,29.452229,59.012016
15,16,satlas_swin_b_naip_si_rgb,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,54.589119,86.369846,59.527649,49.038404,17.810198,60.199499
16,17,ssl4eos12_resnet50_sentinel2_all_moco,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,54.583287,85.298030,56.983948,44.876866,28.393424,57.364167
17,18,terramind_v1_base,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,54.569695,86.026535,59.217697,46.583503,23.296893,57.723849
18,19,resnet50,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,54.443245,86.538010,57.849616,46.732932,21.697800,59.397866
19,20,ssl4eos12_resnet50_sentinel2_all_dino,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,54.320705,85.048224,56.610818,42.300304,29.901060,57.743118
20,21,clay_v1_base,80100fc6-dc1a-4514-b946-341157eaf816,54.229799,85.057839,51.555387,48.238308,25.033952,61.263510
21,22,dinov3_convnext_large,80100fc6-dc1a-4514-b946-341157eaf816,54.095371,85.809534,51.403266,49.836355,23.694962,59.732736
22,23,prithvi_eo_v2_300_tl,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,54.042097,86.870613,58.730443,45.221164,23.979860,55.408404
23,24,ssl4eos12_resnet50_sentinel2_all_decur,114be1f0-5a41-43a5-b4e6-7fb683bc01ec,53.854631,84.521102,56.535177,43.223588,27.755357,57.237930
24,25,dofa_large_patch16_224,80100fc6-dc1a-4514-b946-341157eaf816,53.812794,84.859134,53.556535,48.680676,24.732459,57.235167
25,26,convnext_xlarge_fb_in22k,80100fc6-dc1a-4514-b946-341157eaf816,53.593221,85.685546,53.785298,46.124573,22.748835,59.621851
26,27,prithvi_eo_v2_600_tl,80100fc6-dc1a-4514-b946-341157eaf816,52.083733,84.595304,50.264819,41.347899,25.383111,58.827533
27,28,terramind_v1_large,80100fc6-dc1a-4514-b946-341157eaf816,51.677039,82.876167,48.449737,39.973534,31.652290,55.433468
28,29,ssl4eos12_resnet50_sentinel2_all_decur,80100fc6-dc1a-4514-b946-341157eaf816,50.448895,82.736690,48.766572,39.924277,24.741526,56.075410
29,30,satlas_resnet50_sentinel2_si_ms_satlas,80100fc6-dc1a-4514-b946-341157eaf816,49.444737,81.440641,45.207552,37.586870,27.458513,55.530107
30,31,satlas_swin_b_sentinel2_si_ms,80100fc6-dc1a-4514-b946-341157eaf816,48.398293,80.740008,44.138532,36.724589,23.126621,57.261715